### ISSUE TITLE
Else if are not supported

### ISSUE THREAD

**Issue by gungun974** [vrischmann/tree-sitter-templ#11]
I write this issue very quick cause I'm not done for my work today but I found a bug !

This tree sitter plugin support the `if` and `else` pattern in `templ` but the `else if` of Go is not.

In my treesitter tree I can see some `ERROR` node on when should be `component_if_statement`.

I will look later this day for making a PR to address this issue since I think it should be relativity easy.

But for now I made this Issue as a reminder for myself ^^

**Comment by vrischmann** [comment]
I'm closing this since you fixed it in #12
