### ISSUE TITLE
`/` in markup text breaks highlighting and tree-sitter parse

### ISSUE THREAD

**Issue by andrewmthomas87** [vrischmann/tree-sitter-templ#25]
`/` in markup text breaks highlighting and tree-sitter parse.

Example:

```
package templates

templ OK(errors map[string]string) {
	<p>First or given name</p>
	if err, ok := errors["name-short"]; ok {
		<p style="color: red;">{ err }</p>
	}
}

templ Broken(errors map[string]string) {
	<p>First/given name</p>
	if err, ok := errors["name-short"]; ok {
		<p style="color: red;">{ err }</p>
	}
}
```

In `Broken`, the `/` in the text of the first `p` element appears to break things.

<img width="552" alt="Screenshot 2024-01-16 at 4 16 40 PM" src="https://github.com/vrischmann/tree-sitter-templ/assets/7506142/58e8ef3e-e222-4153-91c5-4574fc2f9f90">

Output of `tree-sitter-subtree`:

<img width="531" alt="Screenshot 2024-01-16 at 4 20 38 PM" src="https://github.com/vrischmann/tree-sitter-templ/assets/7506142/71c9da9e-eb11-495f-b251-772785eba387">

I'm using Helix. I've manually updated the grammar to the most recent commit on `master` (https://github.com/vrischmann/tree-sitter-templ/commit/c3baaab33f1f1032eedd3613cd932284975bd21f).

**Comment by vrischmann** [comment]
Hi,

thanks for reporting the issue. I'll look into it.
