### ISSUE TITLE
installs with no treesitter capabilities

### ISSUE THREAD

**Issue by gamebox** [vrischmann/tree-sitter-templ#3]
Getting zero functionality out of this treesitter grammar due to this issue.  I am on a M1 Macbook Pro.

```
❯ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```

Result of :TsInstallInfo
```
templ              [✓] installed
```

Result of :TSModuleInfo
```
templ               ✗          ✗                      ✗ 
```

```
❯ clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: arm64-apple-darwin22.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by gamebox** [comment]
Looks like the issue is that the queries are not being copied into the rtd.  I don't know why or how it's done in other treesitter grammars, but something isn't quite right with this one.

**Comment by gamebox** [comment]
And even copying the current queries results in only highlighting working, not injections.  This is mostly fine for me for now, but would be great to have the other languages injected.

**Comment by vrischmann** [comment]
Hi. Did you install the repo as a plugin as described [here](https://github.com/vrischmann/tree-sitter-templ#installing-the-plugin) ?

**Comment by gamebox** [comment]
Apparently I didn't see that.  Makes a lot of sense.  Closing, thank you very much.  RTFM twice is necessary sometimes

**Comment by vrischmann** [comment]
to be fair I've added this yesterday, maybe it wasn't there when you looked :)
