### ISSUE TITLE
Feature: Support for spread attributes

### ISSUE THREAD

**Issue by JonnyLoughlin** [vrischmann/tree-sitter-templ#30]
Hi,

Currently, spread attributes don't seem to be supported.

```
<hr
  disabled
  { attrs... }
/>
```
produces an AST of 
```
    (element ; [4:2 - 7:3]
      (self_closing_tag ; [4:2 - 7:3]
        name: (element_identifier) ; [4:3 - 4]
        (attribute ; [5:3 - 10]
          name: (attribute_name)) ; [5:3 - 10]
        (attribute ; [6:3 - 3]
          name: (attribute_name)) ; [6:3 - 3]
        (attribute ; [6:5 - 12]
          name: (attribute_name)) ; [6:5 - 12]
        (attribute ; [6:14 - 14]
          name: (attribute_name)) ; [6:14 - 14]
```
It would be helpful if it was treated as a single attribute node. 

Thanks for all the work you do on this!

**Comment by vrischmann** [comment]
Hi,

thanks for reporting this issue.

The multiple attributes that you get here is actually the parser getting confused, it produces an attribute node for `{`, `attrs...`, `}` because it has no clue about spread attributes. 
I didn't implement parsing for this yet (mainly because I wasn't using it).

I'll look into it.

**Comment by JonnyLoughlin** [comment]
Thank you! I am making a plugin to sort the attribute nodes within elements and it would be helpful if spread attributes were either a single node of type attribute. Even if they were their own specific node type, that would work as well.

**Comment by vrischmann** [comment]
@JonnyLoughlin please take a look at #32, it should do what you want.

**Comment by JonnyLoughlin** [comment]
Looks like it should perfectly solve my issue, thanks!
