### ISSUE TITLE
bug: spread attributes break when passed a struct member

### ISSUE THREAD

**Issue by JonnyLoughlin** [vrischmann/tree-sitter-templ#35]
Hi,

It seems the new spread attributes feature breaks under a specific circumstance.  Given the following as an example
```
type Props struct {
	Attrs templ.Attributes
}

templ test(props Props) {
	<hr
		{ props.Attrs... }
	/>
}
```
the relavant part of the AST that is broken is as follow
```
      (self_closing_tag ; [8:2 - 10:3]
        name: (element_identifier) ; [8:3 - 4]
        (spread_attributes ; [9:3 - 20]
          name: (identifier) ; [9:5 - 9]
          (ERROR ; [9:10 - 15]
            (identifier)) ; [9:11 - 15]
```
Passing a templ.Attributes variable directly doesn't produce the same issue.  

The error is more prevalent in this example:
```
type Props struct {
	Attrs templ.Attributes
}

templ test(props Props) {
	<hr
		{ props.Attrs... }
	/>
	@testScript()
}

script testScript() {
  console.log("Test");
}
```
producing a tree of 
```
(type_declaration ; [3:1 - 5:1]
  (type_spec ; [3:6 - 5:1]
    name: (type_identifier) ; [3:6 - 10]
    type: (struct_type ; [3:12 - 5:1]
      (field_declaration_list ; [3:19 - 5:1]
        (field_declaration ; [4:2 - 23]
          name: (field_identifier) ; [4:2 - 6]
          type: (qualified_type ; [4:8 - 23]
            package: (package_identifier) ; [4:8 - 12]
            name: (type_identifier))) ; [4:14 - 23]
(component_declaration ; [7:1 - 16:1]
  name: (component_identifier) ; [7:7 - 10]
  (parameter_list ; [7:11 - 23]
    (parameter_declaration ; [7:12 - 22]
      name: (identifier) ; [7:12 - 16]
      type: (type_identifier)) ; [7:18 - 22]
  (component_block ; [7:25 - 16:1]
    (ERROR ; [8:2 - 15:22]
      (element_identifier) ; [8:3 - 4]
      (identifier) ; [9:5 - 9]
      (css_property_value) ; [9:11 - 15:21]
```
Oddly enough, removing the semicolon in the script declaration fixes the script declaration but the spread attribute is still showing an error.

Thanks again for all your work on the grammar!  I do intend on learning how the grammars are built so I could help fix bugs myself, I just haven't had the time to start learning.

**Comment by vrischmann** [comment]
I think probably we don't handle accessing a field when using spread attributes, so `{ foo... }` works but `{ foo.bar... }`. Just a thought, I'll look into it.

Regarding the script declaration, I think we could do better with error recovery, IIRC tree-sitter provides way to have better error recovery but I have no clue right now how it works.
