### ISSUE TITLE
Issue with generic templ

### ISSUE THREAD

**Issue by Nuxnuxx** [vrischmann/tree-sitter-templ#39]
Hello, when using the templ TS, i come across a problem.
If i use a generic templ function such as this `templ ServiceList[V pkg.ServiceGeneric](services []V)`
the line up and down from my declaration are not colored
![image](https://github.com/vrischmann/tree-sitter-templ/assets/88590463/b0a5e6e6-7a3b-4080-ac27-775d01f8f472)
Is this a problem of the tree sitter for templ ?

**Comment by vrischmann** [comment]
Generic templ components are not supported (I didn't even know this existed).

I'll look into it in the near future.

**Comment by vrischmann** [comment]
This should be fixed now. It should be available in nvim-treesitter in a couple of days.

**Comment by Nuxnuxx** [comment]
Thanks a lot !
