### ISSUE TITLE
push recent improvements to nvim-treesitter

### ISSUE THREAD

**Issue by jackielii** [vrischmann/tree-sitter-templ#61]
I think the folds etc are not in the upstream https://github.com/nvim-treesitter/nvim-treesitter repo. Can you sync the changes to upstream? Much appreciated!

**Comment by vrischmann** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/pull/6923

now we need to wait for upstream to merge.

**Comment by jackielii** [comment]
Thanks @vrischmann. Are you able to push the rawgo changes there as well? provided you approve and merge. I find adding a local parser and run `TSInstall` now always install the local one... Maybe I just didn't figure it out..

**Comment by vrischmann** [comment]
Yes, once I'll review your changes and it's merged to master it will be picked up automatically by upstream a couple of days later at most.

Usually what works for me when I want to work with my local parser:
* remove `templ` from the `ensure_installed` list in the nvim-treesitter config
* run `TSUninstall templ`
* add this in the nvim config
```
-- For debugging the Templ parser
local parser_configs = require "nvim-treesitter.parsers".get_parser_configs()
parser_configs.templ = {
  install_info = {
    url = "/home/vincent/dev/tree-sitter-templ",
    files = {
      "src/parser.c",
      "src/scanner.c"
    },
  },
}
```

**Comment by jackielii** [comment]
Nice! thanks for the tip!
