### ISSUE TITLE
LazyVim Package

### ISSUE THREAD

**Issue by MaxThom** [vrischmann/tree-sitter-templ#7]
Hi,

I am trying to install it into my lazy vim config.  Looks like I have the `OK Parser: temp` in `:checkhealth`, but the features of the parser are not installed. Here is my config: 

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
      },
    },

    config = function()
      local treesitter_parser_config = require "nvim-treesitter.parsers".get_parser_configs()
      treesitter_parser_config.templ = {
        install_info = {
          url = "https://github.com/vrischmann/tree-sitter-templ.git",
            files = {"src/parser.c", "src/scanner.c"},
            branch = "master",
          },
        }
      vim.treesitter.language.register('templ', 'templ')
    end,
  },
}
```

Any idea on whats missing?
Thanks!

**Comment by vrischmann** [comment]
You're probably missing the queries files. I'm not familiar with lazy vim but the easiest way to get these files would be to install this repository as a plugin, see [the readme](https://github.com/vrischmann/tree-sitter-templ#installing-the-plugin).

**Comment by gmenih** [comment]
@MaxThom You have to install `vrischmann/tree-sitter-templ` plugin - it works by adding it under `dependencies`:


```lua
return {
    {
        "nvim-treesitter/nvim-treesitter",
        event = { "BufReadPre", "BufNewFile" },
        build = ":TSUpdate",
        dependencies = {
            "vrischmann/tree-sitter-templ",
        },
        config = function()
                ...
        end
    }
}
```

**Comment by vrischmann** [comment]
@MaxThom is your problem solved ?

**Comment by sopa0** [comment]
Hi, got the same issue here with a similar setup
Tried adding  "vrischmann/tree-sitter-templ", as a dep for the treesitter spec but I'm not getting syntax highlighting either

**Comment by sopa0** [comment]
For my LazyVim setup, here my plugins/templ.lua file:

```lua
return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "vrischmann/tree-sitter-templ",
    },
    config = function()
      local treesitter_parser_config = require("nvim-treesitter.parsers").get_parser_configs()
      treesitter_parser_config.templ = {
        install_info = {
          url = "https://github.com/vrischmann/tree-sitter-templ.git",
          files = { "src/parser.c", "src/scanner.c" },
          branch = "master",
        },
      }
      vim.treesitter.language.register("templ", "templ")
    end,
  },
}
```

here's my options.lua file:

```lua
vim.filetype.add({
  extension = {
    templ = "templ",
  },
})
```

**Comment by vrischmann** [comment]
I don't know LazyVim so I can't provide support for it specifically, sorry.

But I do want to say that the README is confused/obsolete because I was getting confused myself.

Right now I only need the following to get tree-sitter-templ working:
```
return require("packer").startup(function(use)
    use{"vrischmann/tree-sitter-templ",
        config = function()
            require("tree-sitter-templ").setup({})
        end
    }
end)
```

note the call to the [setup](https://github.com/vrischmann/tree-sitter-templ/blob/master/lua/tree-sitter-templ/init.lua#L22-L42) function which does everything needed to get the parser installed.

So my suggestion is to get LazyVim to also call `setup()` after the plugin has been installed.

(fyi I've submitted the parser to the upstream nvim-treesitter, hopefully it will be accepted soon and this will be much simpler.)

**Comment by sopa0** [comment]
Saw it just got merged into nvim-treesitter, working perfectly well now

**Comment by vrischmann** [comment]
Great :) I'll close this issue now then. @MaxThom you should be able to just use `:TSInstall templ` without special configuration.
