### ISSUE TITLE
Syntax Highlighting broke due to input tag being closed without />

### ISSUE THREAD

**Issue by Madslick** [vrischmann/tree-sitter-templ#74]
![image](https://github.com/user-attachments/assets/657f663d-7ea1-46ff-b090-d213b2a4d735)
Relative line numbers 9 & 13 were not closed with /> so the Register() syntax highlighting broke. The only change I made was closing the input tags with /> and the issue was resolved.
![image](https://github.com/user-attachments/assets/0e38e6c9-fb00-42b1-916e-97b39a28e700)

**Comment by vrischmann** [comment]
Hi,

I took a look and yes we can't parse tag that have no closing tag and also that are not self-closing. 

I always self-close these tags myself (even though I don't think it's required in HTML) so I didn't bother to check.

The following component fails with an error too:
```
templ Foo(text string) {
  <input name="foobar" required>
}
```

I'll have to check how easy (or not) it is to support this.

**Comment by vrischmann** [comment]
So, "self closing tags" apparently [don't exist in HTML](https://templ.guide/syntax-and-usage/elements#tags-must-be-closed), however the Templ documentation says [all tags must be closed](https://templ.guide/syntax-and-usage/elements#tags-must-be-closed).

From my testing this is not actually true, `templ generate` works correctly with the snippet I provided above, although `templ fmt` adds the trailing `/` so it sounds like the "correct" thing to do is to have the trailing slash.
I'm inclined to not do anything about this right now.

**Comment by vrischmann** [comment]
I'm closing this as _wontfix_ for the reasons I stated above.

I'm open to merge a PR that fixes this, if someone wants puts in the work.

**Comment by Madslick** [comment]
@vrischmann 
Thanks for looking into this and the replies. I didn't realize that templ had this rule about tags being closed, that is my fault for not having found that info in the templ guide.  Hopefully anyone else that runs into this themselves may find this post and realize they just need to close their tags!
