### ISSUE TITLE
Bug: grammer does not understand templ receiver methods 

### ISSUE THREAD

**Issue by BerkeleyTrue** [vrischmann/tree-sitter-templ#8]
<img width="561" alt="image" src="https://github.com/vrischmann/tree-sitter-templ/assets/6775919/c9b5cf2a-5c05-427c-9986-9ffb9897cff3">

I'm on the latest version.

Here is the addition of receiver methods in Templ https://github.com/a-h/templ/blob/e8f18b2fae1b2160869c1191ec3889332514a8e1/parser/v2/templateparser_test.go#L41

**Comment by vrischmann** [comment]
Yeah that's not implemented, I didn't realize this was possible. I'll look into it when I have some time.
I'd happily merge a PR too if you feel like implementing this :)

**Comment by vrischmann** [comment]
Fixed with https://github.com/vrischmann/tree-sitter-templ/commit/b5cda6f97ece862972a408e472b79d3cd735d93a
