### ISSUE TITLE
css syntax is not working in css component definitions or 

### ISSUE THREAD

**Issue by BKR-dev** [vrischmann/tree-sitter-templ#9]
when declaring a css component in templ, the css is not properly highlighted outside of the go part.
same goes for inside the css class of a tag, like a button:

![Screenshot 2023-11-02 at 15 30 38](https://github.com/vrischmann/tree-sitter-templ/assets/26764459/e153d483-0c64-436c-9209-f6e6cb595198)

**Comment by BKR-dev** [comment]
i cant assign myself but ill push a PR later @vrischmann

**Comment by BKR-dev** [comment]
is partially adressed in https://github.com/vrischmann/tree-sitter-templ/pull/10

**Comment by vrischmann** [comment]
Hi. 

I'm getting back to this issue to see if it can be closed.

As far as I can tell there were two issues:
* CSS properties not properly highlighted in a CSS component
* Bad highlighting in the class attribute of a tag

The first point was addressed by your PR (#10)

The second point I'm not sure the issue actually still exists; this is what I'm getting right now:

![image](https://github.com/vrischmann/tree-sitter-templ/assets/1916079/7b02bedb-47af-4520-aa5a-36591695b9f3)

@BKR-dev can you confirm the highlighting looks OK for you too ?

**Comment by BKR-dev** [comment]
i think this looks good so i havent yet added more as i think it helps enough. 

happy new year btw!

**Comment by vrischmann** [comment]
Thanks, I'll close this issue then.

Happy new year !
